controllers:
    resource: ../main/Controller/
    type: attribute
    prefix: '/_'
api.user.controllers:
    resource: ../main/Controller/User
    type: attribute
    prefix: '/_/user'
api.user.super.controllers:
    resource: ../main/Controller/Admin
    type: attribute
    prefix: '/_/user/super'
app_user_logout:
    path: /_/user/logout
    methods: GET

# ASSET
api.asset.controllers:
    resource: ../asset/Adapter/Symfony/Presentation/Http/Controller/
    type: attribute
    prefix: '/_'
api.asset.user.controllers:
    resource: ../asset/Adapter/Symfony/Presentation/Http/Controller/User/
    type: attribute
    prefix: '/_/user'
#> ASSET

# THUMBNAIL
api.thumbnails.controllers:
    resource: ../thumbnail/Adapter/Symfony/Presentation/Http/Controller/
    type: attribute
    prefix: '/_'
#> THUMBNAIL
