controllers:
    resource: ../main/Controller/
    type: attribute
    prefix: '/_'
api.user.controllers:
    resource: ../main/Controller/User
    type: attribute
    prefix: '/_/user'
api.user.super.controllers:
    resource: ../main/Controller/Admin
    type: attribute
    prefix: '/_/user/super'
app_user_logout:
    path: /_/user/logout
    methods: GET
