api.entity.controllers:
  resource: ../entity/Adapter/Symfony/Presentation/Http/Controller/
  type: attribute
  prefix: '/_'
api.entity.user.controllers:
  resource: ../entity/Adapter/Symfony/Presentation/Http/Controller/User/
  type: attribute
  prefix: '/_/user'
