services:
  Dullahan\Asset\:
    autowire: true
    autoconfigure: true
    resource: '../asset/'
    exclude:
      - '../asset/Application/Attribute'
      - '../asset/Application/Exception'

  Dullahan\Thumbnail\:
    autowire: true
    autoconfigure: true
    resource: '../thumbnail/'
    exclude:
      - '../thumbnail/Entity/'
      - '../thumbnail/Application/Attribute'
      - '../thumbnail/Application/Exception'

  Dullahan\Main\:
    autowire: true
    autoconfigure: true
    resource: '../main/'
    exclude:
      - '../main/DependencyInjection/'
      - '../main/Entity/'
      - '../main/Attribute/'
      - '../main/Event/'
      - '../main/Reader/'
      - '../main/Document/'
      - '../main/Model/'
      - '../main/Exception/'

  Symfony\Component\HttpKernel\Controller\ArgumentResolver\RequestPayloadValueResolver: '@argument_resolver.request_payload'
