services:
  Dullahan\Asset\:
    autowire: true
    autoconfigure: true
    resource: '../asset/'
    exclude:
      - '../asset/Adapter/Symfony/DependencyInjection'
      - '../asset/Domain/Entity/'
      - '../asset/Domain/Attribute'
      - '../asset/Domain/Exception'

  Dullahan\Thumbnail\:
    autowire: true
    autoconfigure: true
    resource: '../thumbnail/'
    exclude:
      - '../thumbnail/Adapter/Symfony/DependencyInjection'
      - '../thumbnail/Domain/Entity/'
      - '../thumbnail/Domain/Attribute'
      - '../thumbnail/Domain/Exception'

  Dullahan\Main\:
    autowire: true
    autoconfigure: true
    resource: '../main/'
    exclude:
      - '../main/DependencyInjection/'
      - '../main/Entity/'
      - '../main/Attribute/'
      - '../main/Event/'
      - '../main/Reader/'
      - '../main/Document/'
      - '../main/Model/'
      - '../main/Exception/'

  Dullahan\User\:
    autowire: true
    autoconfigure: true
    resource: '../user/'
    exclude:
      - '../user/Adapter/Symfony/Application/DependencyInjection'
      - '../user/Domain/Entity/'
      - '../user/Domain/Exception'

  Dullahan\Object\:
    autowire: true
    autoconfigure: true
    resource: '../object/'
    exclude:
      - '../object/Adapter/Symfony/Application/DependencyInjection'
      - '../object/Domain/Entity/'
      - '../object/Domain/Exception'

  Dullahan\Monitor\:
    autowire: true
    autoconfigure: true
    resource: '../monitor/'
    exclude:
      - '../monitor/Adapter/Symfony/Application/DependencyInjection'
      - '../monitor/Domain/Entity/'
      - '../monitor/Domain/Exception'

  Symfony\Component\HttpKernel\Controller\ArgumentResolver\RequestPayloadValueResolver: '@argument_resolver.request_payload'
